language: objective-c
osx_image: xcode9
before_install:
- gem install cocoapods # Since Travis is not always on latest version
script:
- xcodebuild clean build -project CellAnimator.xcodeproj -scheme CellAnimator ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- pod lib lint
